//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException(); //TODO: enable cascade deleting for descriptors
        }
    
        public virtual DbSet<account> accounts { get; set; }
        public virtual DbSet<exercise> exercises { get; set; }
        public virtual DbSet<feedback> feedbacks { get; set; }
        public virtual DbSet<focuspoint> focuspoints { get; set; }
        public virtual DbSet<member> members { get; set; }
        public virtual DbSet<playsession> playsessions { get; set; }
        public virtual DbSet<position> positions { get; set; }
        public virtual DbSet<practicesession> practicesessions { get; set; }
        public virtual DbSet<practicesessionexercise> practicesessionexercises { get; set; }
        public virtual DbSet<practiceteam> practiceteams { get; set; }
        public virtual DbSet<ranklist> ranklists { get; set; }
        public virtual DbSet<teammatch> teammatches { get; set; }
        public virtual DbSet<token> tokens { get; set; }
    }
}
