
namespace Common
{
    public enum RequestType {
        ConnectionTest,
        Login,
        CreateAccount,
        VerifyLineup,
        GetSchedule,
        GetPracticeTeam,
        GetPlayersWithNoAccount,
        GetAllPlayers,
        GetAllTrainers,
        GetAllMembers,
        GetPlayerFeedback,
        GetPlaySessionFeedback,
        GetPracticeSession,
        GetAllFocusPoints,
        GetMemberPracticeTeams,
        GetPlayerFocusPoints,
        GetTeamMatch,
        GetTeamMatchPositions,
        GetPracticeSessionFocusPoints,
        GetPracticeSessionExercises,
        GetPlayer,
        GetTokenMember,
        GetAdminPage,
        GetAllPracticeTeams,
        GetMember,
        GetFocusPointDescriptor,
        GetTrainerPracticeTeams,
        //Setters below
        SetPlayer,
        SetPlayerFocusPoints,
        SetComment,
        SetPlayerPracticeTeam,
        ChangeTrainerPrivileges,
        SetNonPrivateFocusPoint,
        SetPracticeTeamTrainer,
        SetMemberSex,
        //Deleters below
        DeletePlayerFocusPoint,
        DeletePlayerPracticeTeam,
        DeleteFocusPointDescriptor,
        DeletePracticeTeam,
        GetExercises,
        //Creators below
        CreateFocusPointDescriptor,
        SetExerciseDiscriptor,
        SetPracticeSession,
        SetTeamMatch,
        SetFeedback,
        SetPracticeTeam,
    };
}